spring:
  application:
    name: microservice-discovery-eureka-ha
security:
  basic:
    enabled: true
  user:
    name: user
    password: password


username: user
password: password

# 是用不同的 profile 激活两个 Eureka 节点
---
spring:
  profiles: peer1
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false  # 是否将自己注册到 Eureka Server
    fetch-registry: false  # 是否从 Eureka Server 获取注册信息
    service-url:
      defaultZone: http://${username}:${password}@localhost:8762/eureka/
  instance:
    hostname: peer1
  server:
    eviction-interval-timer-in-ms: 5000


---
spring:
  profiles: peer2
server:
  port: 8762
eureka:
  client:
    register-with-eureka: false  # 是否将自己注册到 Eureka Server
    fetch-registry: false  # 是否从 Eureka Server 获取注册信息
    service-url:
      defaultZone: http://${username}:${password}@localhost:8761/eureka/
  instance:
    hostname: peer2

