server:
  port: 8010


eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8761/eureka/, http://localhost:8762/eureka/
  instance:
    prefer-ip-address: true

user.userServiceUrl: http://localhost:8000


spring:
  application:
    name: microservice-consumer-movie

